### ISSUE TITLE
Use next(error) to handle errors when possible

### ISSUE THREAD

**Issue by alexander-dubinski** [rossberto/be-capstone2-expresso#1]
https://github.com/rossberto/be-capstone2-expresso/blob/a8c33f19867f3b1189fad6f94c670b919be2ad84/api/employees.js#L106

Using next(error) will invoke the default error handler from Express or invoke your custom error handler if you wrote one. Even if your intention was to invoke the default error handler by throwing an error, if you want to use a custom error handler later it becomes more difficult to change is as the app scales. For this reason it is a best practice with express to use next(error).

**Comment by rossberto** [comment]
Got it, useful observation, thank you.

**Comment by rossberto** [comment]
Hello, at last I had time to fix it, done.
I want to highlight that in the course, there is no a lesson explaining the error handling (well, there is an error handling tiny lesson, but there it is never presented the use of "next(error)", in fact it is showed the "if (error) throw error" approach). I was able to understand the issue with the Express documentation http://expressjs.com/en/guide/error-handling.html 
Once again, thank you.
